### ISSUE TITLE
Too many dimension issue

### ISSUE THREAD

**Issue by Mrinal18** [wangyirui/AD_Prediction#2]
Hey i am running your code and getting this error

`2018-04-19 14:45:49 INFO: At 0-th epoch.
Traceback (most recent call last):
  File "main_alextnet.py", line 234, in <module>
    main(options)
  File "main_alextnet.py", line 133, in main
    train_loss, correct_cnt = train(model, train_loader, use_cuda, criterion, optimizer, train_loss_f)
  File "main_alextnet.py", line 158, in train
    for it, train_data in enumerate(train_loader):
  File "/Users/science/Desktop/Alziehmer/my_project/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 281, in __next__
    return self._process_next_batch(batch)
  File "/Users/science/Desktop/Alziehmer/my_project/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 301, in _process_next_batch
    raise batch.exc_type(batch.exc_msg)
ValueError: Traceback (most recent call last):
  File "/Users/science/Desktop/Alziehmer/my_project/lib/python2.7/site-packages/torch/utils/data/dataloader.py", line 55, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "/Users/science/Desktop/Alziehmer/AD_Prediction/AD_2DRandomSlicesData.py", line 60, in __getitem__
    image2D = Image.fromarray(image2D.astype(np.uint8), 'RGB')
  File "/Users/science/Desktop/Alziehmer/my_project/lib/python2.7/site-packages/PIL/Image.py", line 2441, in fromarray
    raise ValueError("Too many dimensions: %d > %d." % (ndim, ndmax))
ValueError: Too many dimensions: 4 > 3.`

Can you help me in solving this problem?

**Comment by wangyirui** [comment]
We did this project last year so some details I might have forgotten. But based on the error message, I think your input image is mismatch with the PIL image API. I strongly suggest you to read python PIL API, understand the meaning of each dimension, and see whether you should transpose two dimensions. I think it wouldn't be hard to  figure it out.

**Comment by wangyirui** [comment]
And also you may need to check our dataloader file to check whether your input image fit our dataloader API.

**Comment by Mrinal18** [comment]
i am confused about the dataloader file, can you elaborate more on that? i cant find any dataloader file. 

And how do i check it?

**Comment by wangyirui** [comment]
@Mrinal18 Sorry for the confusion. I reviewed my code, and it seems your problem comes from line 39 in custom_transpose:
 `img = torch.from_numpy(pic.transpose((2, 0, 1)))
`
I suggest you to check the image shape (use print before this line) to understand what's shape the images have before sending into the function from_numpy. We did transpose here since we want to make our input sarisfy the PyTorch to_tensor API. 

So I think you should do the following this to see whether you can find the mismatch:
1. as I said, check the image shape before line 39 (by using print or other debug skills)
2. read [http://pytorch.org/docs/master/torchvision/transforms.html#conversion-transforms](PyTorch Document) to see what shape the method ToTensor expects.

**Comment by Mrinal18** [comment]
Hey, thank you for your solution it was very helpful.

i had a 4D image which i converted into 3D image using:

`m, n = image2D.shape[::2]`
`image2D = np.rollaxis(image2D, 3, 1).reshape(m, -1, n)`


After this it worked properly. Althought the accuracy and loss are not upto satisfaction.

`Average training loss is 0.77421 at the end of epoch 0`
`Average training accuracy is 0.51970 at the end of epoch 0`

Any suggestions to this?

**Comment by wangyirui** [comment]
Glad  to hear it works! I think firstly, you may need to check whether your reshape make sense (I'm not familiar with this part since my teammate in charge of this part). Secondly, from your training result, I saw you only trained one epoch? Are you training the model on CPU or GPU? Training only one epoch is definitely not enough. In our experiment, we run about 80+ epochs to achieve the reported accuracy (on about 600 training samples).

**Comment by Mrinal18** [comment]
Hey, i am currently training in CPU. and yes, i figured that running one epouch is not enough so i have run the training.

`2018-04-23 19:33:01 INFO: Average training loss is 0.63730 at the end of epoch 3`
`2018-04-23 19:33:01 INFO: Average training accuracy is 0.57508 at the end of epoch 3`

this is the result at epoch 3

And this is the validation accuracy 

`Average validation accuracy is 0.46078 at the end of epoch 3`

**Comment by wangyirui** [comment]
OK. I strongly suggest you train your model on GPUs. If you are a college student and doing a course project, you can apply Google Cloud to have GPU servers (free $50 credit). From my experience, I think $50 is enough to finish training.

**Comment by Mrinal18** [comment]
Thank you for your reply. I did run it in my system before till 103th epoch and the average validation accuracy came out to be 88% approx, which i am sure will increase after more epochs. 

I have one small doubt though, so can i do the classification of an image after this?

**Comment by wangyirui** [comment]
It seems the model works good. One thing you should know is that after you running many epochs, the validation accuracy may start decreasing, which we called overfitting. You may need to stop training after observing this phenomenon. I guess the "classification" you said is prediction. It's easy, check the training code, the validation part is what you need. You should remove the training procedure when doing prediction. And another thing is loading your best model before doing so.  You may use the following code to load the well-trained model.
 `if isinstance(checkpoint, dict) and 'state_dict' in checkpoint:
            model.load_state_dict(checkpoint['state_dict'])
        else:
            model.load_state_dict(checkpoint)`

**Comment by wangyirui** [comment]
test.py may have some problems. You should look at train.py. You may need to train your own model

**Comment by Mrinal18** [comment]
Hey, so i checked your repo again. But i dont think i can find any train.py file. only test.py and test_encoder.py

**Comment by wangyirui** [comment]
@Mrinal18 I mean the file you train the model

**Comment by Mrinal18** [comment]
Hey, So i read somewhere that this "dimension" problem might be coming because of the `batch_size =32`, and suggested that batch_size should be 1.
[https://medium.com/@yvanscher/pytorch-tip-yielding-image-sizes-6a776eb4115b](url)

Kindly, check and see if this is what you did and it is correct.?

**Comment by FaRe3** [comment]
> Hey, So i read somewhere that this "dimension" problem might be coming because of the `batch_size =32`, and suggested that batch_size should be 1.
> [https://medium.com/@yvanscher/pytorch-tip-yielding-image-sizes-6a776eb4115b](url)
> 
> Kindly, check and see if this is what you did and it is correct.?

If the code worked for you can you please guide me through it. I chise this as my college project and i have applied for the dataset on adni website as well.I have read lots of issues so im not sure if i can run this code on my own so can you please guide me 
thank you
